/* HoloDenoise browser client: ONNX U-Net inference with a transparent fallback. */
const $ = (id) => document.getElementById(id);
const state = { input: null, reference: null, output: null, inputName: null, outputName: null, session: null };
const statusBox = document.querySelector('.status-box');

function setStatus(title, text, kind = '') { $('statusTitle').textContent = title; $('statusText').textContent = text; statusBox.className = `status-box ${kind}`; }
function fileToImage(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const img = new Image(); img.onload = () => resolve(img); img.onerror = reject; img.src = reader.result; }; reader.onerror = reject; reader.readAsDataURL(file); }); }
function canvasFromImage(image, width = image.naturalWidth || image.width, height = image.naturalHeight || image.height) { const canvas = document.createElement('canvas'); canvas.width = width; canvas.height = height; canvas.getContext('2d').drawImage(image, 0, 0, width, height); return canvas; }
function canvasToArray(canvas) { const data = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height).data; const values = new Float32Array(canvas.width * canvas.height); for (let i = 0; i < values.length; i++) values[i] = (0.299 * data[i * 4] + 0.587 * data[i * 4 + 1] + 0.114 * data[i * 4 + 2]) / 255; return values; }
function showImage(stageId, imageOrCanvas, alt) { const stage = $(stageId); stage.innerHTML = ''; const img = document.createElement('img'); img.alt = alt; img.src = imageOrCanvas instanceof HTMLCanvasElement ? imageOrCanvas.toDataURL('image/png') : imageOrCanvas.src; stage.appendChild(img); }
function imageInfo(image) { return `${image.naturalWidth || image.width} × ${image.naturalHeight || image.height} px`; }

async function loadInput(fileOrImage, label = '输入图') { state.input = fileOrImage instanceof File ? await fileToImage(fileOrImage) : fileOrImage; showImage('inputStage', state.input, label); $('inputInfo').textContent = imageInfo(state.input); $('outputStage').innerHTML = '<div class="empty-state"><span class="empty-icon">✦</span><span>运行推理后显示结果</span></div>'; $('outputInfo').textContent = '等待推理'; state.output = null; setStatus('输入图已就绪', '点击“开始去噪”运行模型'); }
async function loadReference(fileOrImage) { state.reference = fileOrImage instanceof File ? await fileToImage(fileOrImage) : fileOrImage; showImage('referenceStage', state.reference, 'Clean reference'); $('referenceInfo').textContent = imageInfo(state.reference); if (state.output) updateMetrics(); }

async function loadModel() { if (state.session) return; if (!window.ort) throw new Error('ONNX Runtime Web 未加载，请检查网络或 CDN。'); ort.env.wasm.wasmPaths = 'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.19.2/dist/'; setStatus('正在加载模型', '首次加载约需几秒…'); state.session = await ort.InferenceSession.create('model.onnx', { executionProviders: ['wasm'], graphOptimizationLevel: 'all' }); state.inputName = state.session.inputNames[0]; state.outputName = state.session.outputNames[0]; }

function paddedInput(image) { const base = canvasFromImage(image); const original = { width: base.width, height: base.height }; const padW = (8 - base.width % 8) % 8; const padH = (8 - base.height % 8) % 8; const padded = document.createElement('canvas'); padded.width = base.width + padW; padded.height = base.height + padH; const ctx = padded.getContext('2d'); ctx.fillStyle = '#000'; ctx.fillRect(0, 0, padded.width, padded.height); ctx.drawImage(base, 0, 0); return { values: canvasToArray(padded), width: padded.width, height: padded.height, original, base }; }
function canvasFromValues(values, width, height, original) { const canvas = document.createElement('canvas'); canvas.width = original.width; canvas.height = original.height; const ctx = canvas.getContext('2d'); const out = ctx.createImageData(width, height); for (let i = 0; i < values.length; i++) { const v = Math.max(0, Math.min(255, Math.round(values[i] * 255))); out.data[i * 4] = v; out.data[i * 4 + 1] = v; out.data[i * 4 + 2] = v; out.data[i * 4 + 3] = 255; } const full = document.createElement('canvas'); full.width = width; full.height = height; full.getContext('2d').putImageData(out, 0, 0); ctx.drawImage(full, 0, 0, original.width, original.height); return canvas; }

function fallbackDenoise(values, width, height) { const out = new Float32Array(values.length); for (let y = 0; y < height; y++) for (let x = 0; x < width; x++) { let sum = 0, weight = 0; const center = values[y * width + x]; for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) { const xx = Math.max(0, Math.min(width - 1, x + dx)); const yy = Math.max(0, Math.min(height - 1, y + dy)); const v = values[yy * width + xx]; const w = Math.exp(-Math.abs(v - center) * 18); sum += v * w; weight += w; } out[y * width + x] = sum / weight; } return out; }

async function runInference() { if (!state.input) { alert('请先打开一张带噪图。'); return; } $('runBtn').disabled = true; try { const prepared = paddedInput(state.input); let values; let mode = 'ONNX U-Net'; try { await loadModel(); const tensor = new ort.Tensor('float32', prepared.values, [1, 1, prepared.height, prepared.width]); const result = await state.session.run({ [state.inputName]: tensor }); values = result[state.outputName].data; } catch (modelError) { console.warn(modelError); values = fallbackDenoise(prepared.values, prepared.width, prepared.height); mode = '浏览器近似滤波'; } state.output = canvasFromValues(values, prepared.width, prepared.height, prepared.original); showImage('outputStage', state.output, 'Denoised output'); $('outputInfo').textContent = `${imageInfo(state.output)} · ${mode}`; updateMetrics(); setStatus('推理完成', `${mode} · 图像仅在本地浏览器处理`, 'ready'); } catch (error) { console.error(error); setStatus('推理失败', error.message, 'error'); alert(`推理失败：${error.message}`); } finally { $('runBtn').disabled = false; } }

function metrics(a, b) { if (!a || !b || a.length !== b.length) return null; let mse = 0, ma = 0, mb = 0; for (let i = 0; i < a.length; i++) { mse += (a[i] - b[i]) ** 2; ma += a[i]; mb += b[i]; } mse /= a.length; ma /= a.length; mb /= a.length; let va = 0, vb = 0, cov = 0; for (let i = 0; i < a.length; i++) { va += (a[i] - ma) ** 2; vb += (b[i] - mb) ** 2; cov += (a[i] - ma) * (b[i] - mb); } va /= a.length; vb /= a.length; cov /= a.length; const c1 = 0.01 ** 2, c2 = 0.03 ** 2; const ssim = ((2 * ma * mb + c1) * (2 * cov + c2)) / ((ma ** 2 + mb ** 2 + c1) * (va + vb + c2)); return { psnr: mse <= 1e-12 ? 99 : 10 * Math.log10(1 / mse), ssim }; }
function updateMetrics() { if (!state.reference || !state.input || !state.output) return; const ref = canvasFromImage(state.reference, state.input.naturalWidth || state.input.width, state.input.naturalHeight || state.input.height); const a = canvasToArray(canvasFromImage(state.input, ref.width, ref.height)); const b = canvasToArray(canvasFromImage(state.output, ref.width, ref.height)); const c = canvasToArray(ref); const before = metrics(a, c), after = metrics(b, c); $('psnrBefore').textContent = before.psnr.toFixed(2); $('psnrAfter').textContent = after.psnr.toFixed(2); $('ssimBefore').textContent = before.ssim.toFixed(3); $('ssimAfter').textContent = after.ssim.toFixed(3); }
function saveOutput() { if (!state.output) { alert('请先执行去噪。'); return; } const a = document.createElement('a'); a.download = 'hologram_denoised.png'; a.href = state.output.toDataURL('image/png'); a.click(); }

$('inputFile').addEventListener('change', (e) => e.target.files[0] && loadInput(e.target.files[0])); $('referenceFile').addEventListener('change', (e) => e.target.files[0] && loadReference(e.target.files[0])); $('runBtn').addEventListener('click', runInference); $('saveBtn')?.addEventListener('click', saveOutput); $('sampleBtn').addEventListener('click', async () => { const image = new Image(); image.onload = () => loadInput(image, '仿真带噪样本'); image.src = 'assets/sample_noisy.png'; const clean = new Image(); clean.onload = () => loadReference(clean); clean.src = 'assets/sample_clean.png'; });
document.addEventListener('dragover', (e) => e.preventDefault()); document.addEventListener('drop', (e) => { e.preventDefault(); const file = e.dataTransfer.files[0]; if (file && file.type.startsWith('image/')) loadInput(file); });
